general:
  project_name: test_project
  camera_type: DSLR
  camera_model: D7000
camera_settings:
  exposure_auto: ''
  exposure_time: ''
  gain_auto: ''
  gain_level: ''
  gamma: ''
  balance_ratio_red: ''
  balance_ratio_blue: ''
  shutterspeed: 1/50
  aperture: 3.5
  iso: 500
  whitebalance: Auto
  compression: JPEG (FINE)
scanner_settings:
  x_min: 0.0
  x_max: 450.0
  x_step: 50.0
  y_min: 0.0
  y_max: 1600.0
  y_step: 80.0
  z_min: -20000.0
  z_max: -8000.0
  z_step: 500.0
stacking:
  stack_images: false
  threshold_images: false
  threshold: 1.0
  display_focus_check: false
  additional_sharpening: false
masking:
  mask_images: false
  masking_focus_threshold: 20
  masking_saturation_threshold: 70
flash:
  flash_length: 300
  flash_delay: 100
exif_data:
  Make: NIKON CORPORATION
  Model: NIKON D7000
  SerialNumber: '6174198'
  Lens: Nikkor
  CameraSerialNumber: '6174198'
  LensManufacturer: Nikon
  LensModel: 18 - 105 f / 3.5
  FocalLength: '18'
  FocalLengthIn35mmFormat: '27.0'
